import "~/styles/globals.css";

import { type Metadata } from "next";
import { Jost, Marcellus } from 'next/font/google'
import { Providers } from "./provider";
import { Toaster } from "~/components/ui/toaster";


const text = Marcellus({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-heading",
});

const heading = Jost({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-text",
});


export const metadata: Metadata = {
  title: "SSEHA | CMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${text.variable} ${heading.variable}`}>
      <body className="grid grid-cols-12">
        <Providers>
          {children}
          <Toaster/>
        </Providers>
      </body>
    </html>
  );
}
